version: "3"

services:
  fastapi-server:
    container_name: fastapi-server-container
    build :
      context: .
      dockerfile: Dockerfile
    ports : 
      - "80:80"
    volumes :
      - "./:/app"
    restart : always
    
    