version: "3"

services:
  db-server:
    container_name: db-server
    image : 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      # - MYSQL_ROOT_USER=root
      - MYSQL_HOST=${DB_HOST}
      # - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ="Asia/Seoul"
    ports:
      - '3306:3306'
    restart : always
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping"]
      timeout: 20s
      retries: 3

  laundrydo-server:
    container_name: laundrydo-server
    build : .
    restart : always
    depends_on : 
      db-server :
        condition : service_healthy
    build :
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=app
      - API_TITLE=LAUNDRYDO
      - API_DESCRIPTION=laundry service
      - API_VERSION=0.1
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["./run.sh"]
    ports:
      - "8000:8000"
    