version: "3"

services:
  db-server:
    container_name: db
    image : 'mysql'
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD} # replace by environment on CI
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ="Asia/Seoul"
    env_file :
      - .env

    expose :
      - 3306
    # volumes :
    #   - ./mysql/conf.d:/etc/mysql/conf.d
    #   - ./mysql/data:/var/lib/mysql
      
    # env_file: .env
    restart : always
    # healthcheck: 
      # test: curl -fsS mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE} || exit 1                                # ${DB_HOST}:${DB_PORT}/{DB_DATABASE} || exit 1
      # test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      # timeout: 10s
      # retries: 3

  

  
  fastapi-server:
    container_name: fastapi-server-container
    depends_on : 
      - db-server 
        # condition : service_healthy
    links :
      - db-server
    # command : sh -c "sleep 5"
    build :
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_HOST="app"
      - PYTHONDONTWRITEBYTECODE=1
    env_file : 
      - .env
    ports : 
      - "80:80"
    volumes :
      - "./:/app"
    restart : always
    