version: "3"

services:
  db-server:
    container_name: db
    image : 'mysql'
    environment:
      MYSQL_DATABASE: 'laundrydo'
      MYSQL_ROOT_PASSWORD: 'test1234' # replace by environment on CI
    ports :
      - "3306:3306"
    volumes :
      - "./db:/app/db"
    restart : always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    
  fastapi-server:
    container_name: fastapi-server-container
    depends_on : 
      - db-server
    build :
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db-server
      - DB_PASSWORD=test1234
      - API_HOST=app
      - PYTHONDONTWRITEBYTECODE=1
    ports : 
      - "80:80"
    volumes :
      - "./:/app"
    restart : always
    