version: "3"

services:
  db-server:
    image : 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ="Asia/Seoul"
    # ports:
    #   - '3306:3306'
    expose : 
      - 3306
    restart : always
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping"]
      timeout: 20s
      retries: 3
    networks :
      - my_network

  laundrydo-server:
    container_name: laundrydo-server
    build : .
    restart : always
    depends_on : 
      db-server :
        condition : service_healthy
    environment:
      - API_HOST=app
      - API_TITLE=LAUNDRYDO
      - API_DESCRIPTION=laundry service
      - API_VERSION=0.1
      - PYTHONDONTWRITEBYTECODE=1
    command : ["sh", "./run.sh"]
    networks :
      - my_network
    ports:
      - "8001:8000"
    
networks:
  my_network: