"""empty message

Revision ID: 2e16122a3316
Revises: 
Create Date: 2023-10-11 21:28:33.684562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e16122a3316'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.drop_column('machine', 'start_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('start_at', sa.DATETIME(), nullable=True))
    op.drop_column('machine', 'started_at')
    # ### end Alembic commands ###
