"""empty message

Revision ID: 639b624cb75d
Revises: 51f490535c4c
Create Date: 2023-10-19 15:19:15.367574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639b624cb75d'
down_revision: Union[str, None] = '51f490535c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
