name: Create Issue Branch


on:
    issues : 
        types : [assigned]
    issue_comment :
        types: [created]
    pull_request: 
        types : [closed]


jobs : 
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
            - name : Create_Issue_Branch
              uses : robvanderleek/create-issue-branch@main
              env : 
                    GITHUB_TOKEN: ${{ secrets.TOKEN }}
            - name: Echo Branch name
              run : echo ${{ steps.create_issue_branch_job.outputs.branchName }}
    